const BASE = '/taj-restaurant';

export const BUSINESS = {
  nameEn: 'Taj Restaurant',
  nameAr: 'مطعم تاج',
  taglineEn: 'Royal Indian Flavors in the Heart of Muscat',
  taglineAr: 'نكهات هندية ملكية في قلب مسقط',
  descEn:
    'Taj Restaurant brings the opulent flavors of royal Indian cuisine to Muscat. From slow-simmered biryanis to tandoor-fired naans, every dish celebrates centuries of Mughlai culinary tradition — a regal dining experience for every occasion.',
  descAr:
    'يُقدم مطعم تاج نكهات المطبخ الهندي الملكي في قلب مسقط. من البرياني المطبوخ على نار هادئة إلى الخبز المشوي في التندور، كل طبق يحتفي بقرون من التراث الطهوي المغولي.',
  cuisine: 'Indian · Mughlai',
  city: 'Muscat, Oman',
  address: 'Al Ghubra, Muscat, Oman',
  phone: '+968 2449 5500',
  whatsapp: '+96824495500',
  rating: 4.7,
  reviews: 1243,
  established: 2005,
  hours: {
    weekdays: '11:30 AM – 11:30 PM',
    weekends: '11:30 AM – 1:00 AM',
  },
  highlights: [
    { en: 'Authentic Mughlai Recipes', ar: 'وصفات مغولية أصيلة' },
    { en: 'Tandoor-Fired Breads', ar: 'خبز مشوي في التندور' },
    { en: 'Royal Biryani Dum', ar: 'برياني دم ملكي' },
    { en: 'Saffron & Slow-Cooked Curries', ar: 'كاري بالزعفران يُطبخ ببطء' },
  ],
  marqueeItems: [
    'مطعم تاج',
    'ROYAL',
    'MUGHLAI',
    'برياني دم',
    'TANDOOR FIRED',
    'زعفران',
    'HANDCRAFTED',
    'باتر تشيكن',
    'SINCE 2005',
    'دال ماخاني',
    'CRAFTED',
    'MUSCAT',
    'مسقط · عُمان',
    'ROGAN JOSH',
  ],
  orbitLabels: [
    { en: 'Biryani Dum', ar: 'برياني دم' },
    { en: 'Butter Chicken', ar: 'باتر تشيكن' },
    { en: 'Rogan Josh', ar: 'روغان جوش' },
    { en: 'Garlic Naan', ar: 'نان بالثوم' },
    { en: 'Dal Makhani', ar: 'دال ماخاني' },
    { en: 'Gulab Jamun', ar: 'جلاب جامون' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'برياني دم الملكي',
      nameEn: 'Royal Dum Biryani',
      descAr: 'أرز بسمتي بالزعفران مطبوخ على نار هادئة مع لحم الضأن والتوابل الهندية الأصيلة',
      descEn: 'Saffron basmati layered with tender lamb and aromatic spices, slow-cooked in a sealed pot',
      price: '4.8 OMR',
      category: 'أطباق رئيسية',
      img: `${BASE}/menu-biryani.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'باتر تشيكن',
      nameEn: 'Butter Chicken',
      descAr: 'دجاج تندوري في صلصة طماطم كريمية غنية بالزبدة والتوابل',
      descEn: 'Tandoor-charred chicken in a velvety tomato-butter sauce with fenugreek',
      price: '3.9 OMR',
      category: 'كاري',
      img: `${BASE}/menu-butter-chicken.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'روغان جوش',
      nameEn: 'Rogan Josh',
      descAr: 'كاري لحم كشميري غني باللون القرمزي والتوابل العطرية',
      descEn: 'Slow-braised Kashmiri lamb in deep crimson gravy with whole aromatic spices',
      price: '4.2 OMR',
      category: 'كاري',
      img: `${BASE}/menu-rogan.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'نان بالثوم والزبدة',
      nameEn: 'Garlic Butter Naan',
      descAr: 'خبز طري محشو بالثوم والزبدة مشوي في فرن التندور الحجري',
      descEn: 'Pillowy flatbread brushed with garlic butter and baked in a clay tandoor',
      price: '0.8 OMR',
      category: 'خبز',
      img: `${BASE}/menu-naan.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'دال ماخاني',
      nameEn: 'Dal Makhani',
      descAr: 'عدس أسود مطبوخ طوال الليل مع الزبدة والكريمة — طبق كلاسيكي من بنجاب',
      descEn: 'Black lentils slow-simmered overnight with butter and cream — a Punjab classic',
      price: '2.5 OMR',
      category: 'نباتي',
      img: `${BASE}/menu-dal.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'جلاب جامون',
      nameEn: 'Gulab Jamun',
      descAr: 'كرات الحليب المقلية في شراب الورد والهيل — حلوى هندية ملكية',
      descEn: 'Milk-solid dumplings fried golden and soaked in rose water cardamom syrup',
      price: '1.2 OMR',
      category: 'حلويات',
      img: `${BASE}/menu-gulab.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠٠٥',
      titleEn: 'A Crown is Born',
      titleAr: 'ولادة التاج',
      textEn:
        'Taj Restaurant opened in Muscat with a singular vision: to bring the grandeur of Mughlai royal kitchens to the Gulf.',
      textAr: 'افتتح مطعم تاج في مسقط بهدف واحد: إحضار روعة المطابخ الملكية المغولية إلى الخليج.',
    },
    {
      year: '٢٠١٤',
      titleEn: 'The Spice Vault',
      titleAr: 'خزانة التوابل',
      textEn:
        'Expanded our kitchen with a dedicated tandoor room and a private spice blend sourced directly from Rajasthan markets.',
      textAr: 'وسعنا مطبخنا بغرفة تندور مخصصة وخلطة توابل خاصة تُستورد مباشرة من أسواق راجستان.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Royal Table',
      titleAr: 'المائدة الملكية',
      textEn:
        'Over 20 years of culinary excellence in Muscat — every saffron grain, every slow-simmered pot, a tribute to India\'s grandest cuisine.',
      textAr: 'أكثر من ٢٠ عاماً من التميز الطهوي في مسقط — كل خيط زعفران وكل إناء يُطبخ ببطء تحية للمطبخ الهندي العظيم.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Regal Flavors',
      headlineAr: 'نكهات ملكية',
      subEn: 'Authentic Mughlai cuisine in the heart of Muscat',
      subAr: 'مطبخ مغولي أصيل في قلب مسقط',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Saffron & Soul',
      headlineAr: 'زعفران وروح',
      subEn: 'Every biryani slow-cooked to perfection',
      subAr: 'كل برياني يُطبخ ببطء على نار هادئة',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Fire & Spice',
      headlineAr: 'نار وتوابل',
      subEn: 'Tandoor-fired breads and curries crafted with love',
      subAr: 'خبز التندور والكاري مُعدّ بمحبة',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Royal Dining Hall' },
    { src: `${BASE}/gallery2.jpg`, caption: 'The Tandoor Kitchen' },
    { src: `${BASE}/gallery3.jpg`, caption: 'Biryani Dum' },
    { src: `${BASE}/gallery4.jpg`, caption: 'Golden Ambiance' },
    { src: `${BASE}/gallery5.jpg`, caption: 'The Spice Table' },
  ],
  testimonials: [
    {
      nameEn: 'Khalid Al Rashdi',
      nameAr: 'خالد الرشدي',
      rating: 5,
      textEn: 'The best biryani I have ever tasted in Oman. The saffron aroma fills the whole room — absolutely royal.',
      textAr: 'أفضل برياني تذوقته في عُمان على الإطلاق. عبق الزعفران يملأ القاعة — ملكي حقاً.',
      service: 'Royal Dum Biryani',
    },
    {
      nameEn: 'Fatima Al Lawati',
      nameAr: 'فاطمة اللواتية',
      rating: 5,
      textEn: 'The butter chicken here is unmatched. Creamy, rich and perfectly spiced — I bring every guest who visits Muscat.',
      textAr: 'الباتر تشيكن هنا لا مثيل له. كريمي وغني ومتبل بإتقان — أحضر كل ضيف يزور مسقط.',
      service: 'Butter Chicken',
    },
    {
      nameEn: 'Jobins James',
      nameAr: 'جوبينس جيمس',
      rating: 5,
      textEn: 'Amazing experience at Taj Restaurant! Excellent service and very friendly staff. Highly recommend to everyone.',
      textAr: 'تجربة رائعة في مطعم تاج! خدمة ممتازة وطاقم عمل ودود جداً. أنصح به بشدة.',
      service: 'Dining Experience',
    },
    {
      nameEn: 'Noor Al Habsi',
      nameAr: 'نور الحبسي',
      rating: 5,
      textEn: 'The garlic naan straight from the tandoor is something else entirely. Warm, fragrant, and impossibly soft.',
      textAr: 'نان الثوم الطازج من التندور شيء آخر تماماً. دافئ وعطري وطري بشكل لا يُصدق.',
      service: 'Garlic Butter Naan',
    },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3651.0!2d58.3960488!3d23.5906654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91ff007da6768b%3A0xc854a48950559764!2sTaj%20Restaurant%20%7C%20%D9%85%D8%B7%D8%B9%D9%85%20%D8%AA%D8%A7%D8%AC!5e0!3m2!1sen!2som!4v1718000000000!5m2!1sen!2som',
  mapsUrl: 'https://maps.app.goo.gl/d2xwAeEv1aPB1o2h8',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
export const RED_ACCENT = '#C0392B';
