name = "tawaheen-site"
main = "worker-tawaheen.js"
compatibility_date = "2024-01-01"
account_id = "26638150902bc9aee806c25fb3a1a06c"

[[routes]]
pattern = "tawaheen.nounmotion.store"
custom_domain = true

[[routes]]
pattern = "tah.nounmotion.store"
custom_domain = true
