const UNS = 'https://images.unsplash.com';

export const BUSINESS = {
  nameEn: 'Misk Restaurant',
  nameAr: 'مطعم مسك',
  taglineEn: 'The Soul of Lebanon in Muscat',
  taglineAr: 'روح لبنان في قلب مسقط',
  descEn:
    'From slow-simmered stews to charcoal-grilled mezze, Misk brings the vibrant flavors of Beirut straight to Muscat. Every dish is a hand-crafted ode to the Lebanese table — generous, warm, and unforgettable.',
  descAr:
    'من اليخنات المطهوّة ببطء إلى المزة المشوية على الفحم، يُحضر مسك نكهات بيروت الحيّة إلى مسقط. كل طبق قصيدة مكتوبة بالنكهة — كريمة، دافئة، وتبقى في الذاكرة.',
  cuisine: 'Lebanese · Levantine',
  city: 'Muscat, Oman',
  address: 'Muscat, Sultanate of Oman',
  phone: '+968 2400 0000',
  whatsapp: '+96824000000',
  rating: 4.7,
  reviews: 1240,
  established: 2015,
  hours: {
    weekdays: '12:00 PM – 11:30 PM',
    weekends: '12:00 PM – 1:00 AM',
  },
  highlights: [
    { en: 'Authentic Lebanese Recipes', ar: 'وصفات لبنانية أصيلة' },
    { en: 'Charcoal-Grilled Mezze', ar: 'مزة مشوية على الفحم' },
    { en: 'Hand-Rolled Kibbeh', ar: 'كبة مصنوعة يدوياً' },
    { en: 'Warm Levantine Ambiance', ar: 'أجواء شرقية دافئة' },
  ],
  marqueeItems: [
    'مطعم مسك',
    'AUTHENTIC',
    'LEBANESE',
    'حمص طازج',
    'CHARCOAL GRILLED',
    'تبولة',
    'HANDCRAFTED',
    'كباب لبناني',
    'SINCE 2015',
    'فتوش',
    'CRAFTED',
    'MUSCAT',
    'مسقط · عُمان',
    'SEASONAL',
  ],
  orbitLabels: [
    { en: 'Hummus', ar: 'حمص' },
    { en: 'Kibbeh', ar: 'كبة' },
    { en: 'Tabbouleh', ar: 'تبولة' },
    { en: 'Shawarma', ar: 'شاورما' },
    { en: 'Fattoush', ar: 'فتوش' },
    { en: 'Mezze', ar: 'مزة' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'مزة لبنانية ملكية',
      nameEn: 'Royal Lebanese Mezze',
      descAr: 'تشكيلة فاخرة من حمص الكريمي، مطبل الدخاني، وكبة مقلية مع خبز مرقوق طازج',
      descEn: 'Lavish spread of creamy hummus, smoky mutabbal, golden kibbeh and fresh marqouq bread',
      price: '5.5 OMR',
      category: 'مزة',
      img: `${UNS}/photo-1542345542-0e1f5e3c0cd6?auto=format&fit=crop&w=800&q=80`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'شاورما لبنانية',
      nameEn: 'Lebanese Shawarma',
      descAr: 'دجاج متبل بالبهارات اللبنانية على الحجر مع ثوم وخيار',
      descEn: 'Spiced chicken on the spit, garlic sauce, pickles in fresh bread',
      price: '2.8 OMR',
      category: 'مشاوي',
      img: `${UNS}/photo-1529694157872-4e0c0f3b238b?auto=format&fit=crop&w=600&q=80`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'حمص بالطحينة',
      nameEn: 'Classic Hummus',
      descAr: 'حمص كريمي بالطحينة الأصيلة وزيت الزيتون البكر والكمون',
      descEn: 'Silky hummus, authentic tahini, extra-virgin olive oil and cumin',
      price: '1.5 OMR',
      category: 'مقبلات',
      img: `${UNS}/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=600&q=80`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'تبولة طازجة',
      nameEn: 'Fresh Tabbouleh',
      descAr: 'بقدونس وطماطم وبرغل وليمون وزيت زيتون — سلطة الشرق الأول',
      descEn: 'Parsley, tomatoes, bulgur, lemon, olive oil — the Levant\'s finest salad',
      price: '1.8 OMR',
      category: 'سلطات',
      img: `${UNS}/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'كبة مشوية',
      nameEn: 'Grilled Kibbeh',
      descAr: 'كبة لحم البقر بالبهارات اللبنانية مشوية على الفحم مع الزبادي',
      descEn: 'Spiced beef kibbeh charcoal-grilled, served with cool yoghurt',
      price: '3.2 OMR',
      category: 'مشاوي',
      img: `${UNS}/photo-1574484284002-952d92456975?auto=format&fit=crop&w=600&q=80`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'كنافة بالقشطة',
      nameEn: 'Knafeh bil Qishta',
      descAr: 'كنافة دافئة بالقشطة الناعمة وعجينة الكاداييف وشراب الورد',
      descEn: 'Warm kataifi pastry, clotted cream, rosewater syrup — pure indulgence',
      price: '2.0 OMR',
      category: 'حلويات',
      img: `${UNS}/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=600&q=80`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠١٥',
      titleEn: 'A Beirut Dream',
      titleAr: 'حلم بيروتي',
      textEn:
        'Born in the heart of Muscat with a single mission: to recreate the soul of the Lebanese table — vibrant, generous, and deeply personal.',
      textAr: 'وُلد في قلب مسقط بهدف واحد: إعادة خلق روح المائدة اللبنانية — حيّة، كريمة، وعميقة الجذور.',
    },
    {
      year: '٢٠١٩',
      titleEn: 'The Garden Room',
      titleAr: 'قاعة الحديقة',
      textEn:
        'Expanded with an al-fresco terrace inspired by Beirut\'s famous Mar Mikhael quarter — pergolas, lanterns, and the scent of jasmine.',
      textAr: 'توسعنا بتراس مفتوح مستوحى من حي مار مخايل البيروتي — معرشات وفوانيس وعطر الياسمين.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Living Table',
      titleAr: 'مائدة حية',
      textEn:
        'Over a decade of crafting memories in Muscat — every kibbeh, every mezze, a love letter to the Lebanese coast.',
      textAr: 'أكثر من عقد من صنع الذكريات في مسقط — كل كبة وكل مزة رسالة حب إلى الساحل اللبناني.',
    },
  ],
  heroSlides: [
    {
      img: `${UNS}/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1920&q=80`,
      headlineEn: 'Taste of Beirut',
      headlineAr: 'نكهة بيروت',
      subEn: 'Authentic Lebanese cuisine crafted daily in Muscat',
      subAr: 'مطبخ لبناني أصيل يُصنع يومياً في مسقط',
    },
    {
      img: `${UNS}/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1920&q=80`,
      headlineEn: 'Fire & Mezze',
      headlineAr: 'نار ومزة',
      subEn: 'Every skewer charcoal-grilled to perfection',
      subAr: 'كل سيخ يُشوى على الفحم بإتقان',
    },
    {
      img: `${UNS}/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1920&q=80`,
      headlineEn: 'Crafted Daily',
      headlineAr: 'يُصنع يومياً',
      subEn: 'Hummus, tabbouleh and kibbeh made fresh every morning',
      subAr: 'حمص وتبولة وكبة طازجة كل صباح',
    },
  ],
  galleryImages: [
    {
      src: `${UNS}/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=800&q=80`,
      caption: 'The Dining Hall',
    },
    {
      src: `${UNS}/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80`,
      caption: 'The Grill',
    },
    {
      src: `${UNS}/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80`,
      caption: 'The Mezze Kitchen',
    },
    {
      src: `${UNS}/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80`,
      caption: 'Levantine Ambiance',
    },
    {
      src: `${UNS}/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80`,
      caption: 'Signature Plates',
    },
  ],
  testimonials: [
    {
      nameEn: 'Khalid Al Busaidi',
      nameAr: 'خالد البوسعيدي',
      rating: 5,
      textEn: 'The hummus and tabbouleh are the best I\'ve had in Oman — fresh, perfectly balanced, just like in Beirut.',
      textAr: 'الحمص والتبولة هنا أفضل ما تذوقته في عُمان — طازج ومتوازن تماماً كما في بيروت.',
      service: 'Lebanese Mezze',
    },
    {
      nameEn: 'Aisha Al Harthi',
      nameAr: 'عائشة الحارثي',
      rating: 5,
      textEn: 'The atmosphere is warm and inviting — the lanterns and arches made me feel like I was dining in a Beirut garden.',
      textAr: 'الأجواء دافئة ومرحبة — الفوانيس والأقواس جعلتني أشعر كأنني أتناول الطعام في حديقة بيروتية.',
      service: 'Dining Experience',
    },
    {
      nameEn: 'Mohammed Al Zadjali',
      nameAr: 'محمد الزدجالي',
      rating: 5,
      textEn: 'Their knafeh is extraordinary — the rosewater syrup and warm pastry is pure comfort. We order it every single visit.',
      textAr: 'الكنافة استثنائية — شراب الورد والعجينة الدافئة راحة خالصة. نطلبها في كل زيارة.',
      service: 'Knafeh bil Qishta',
    },
    {
      nameEn: 'Fatima Al Rawahi',
      nameAr: 'فاطمة الرواحي',
      rating: 5,
      textEn: 'Family dinner here is always a celebration. The mezze spread is generous beyond belief and the service is truly warm.',
      textAr: 'العشاء العائلي هنا احتفال دائماً. المزة سخية بشكل لا يُصدق والخدمة دافئة من القلب.',
      service: 'Family Dinner',
    },
  ],
  dishOrbitImg: `${UNS}/photo-1544510807-ac2f7a249b57?auto=format&fit=crop&w=600&q=80`,
  storyBg: `${UNS}/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1920&q=80`,
  reservationBg: `${UNS}/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1920&q=80`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14499.54!2d58.3966928!3d23.5730819!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91ff0ecbc8908d%3A0xcefef1c34dee41ee!2sMisk%20Restaurant%20Oman!5e0!3m2!1sen!2som!4v1718000000000!5m2!1sen!2som',
  mapsUrl: 'https://maps.app.goo.gl/jCwwwGLV4ZV5FUWz7',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
