const BASE = '/turkish-house';

export const BUSINESS = {
  nameEn: 'Turkish House Restaurant',
  nameAr: 'مطعم البيت التركي',
  taglineEn: 'The Taste of Turkey in the Heart of Muscat',
  taglineAr: 'طعم تركيا في قلب مسقط',
  descEn:
    'Nestled in the heart of Muscat, Turkish House Restaurant brings the rich flavors of Ottoman cuisine to Oman. From slow-roasted kebabs to hand-rolled baklava, every dish is a tribute to Turkey\'s culinary heritage.',
  descAr:
    'في قلب مسقط، يقدم مطعم البيت التركي نكهات المطبخ العثماني الأصيل. من الكباب المشوي إلى البقلاوة المعجونة يدوياً، كل طبق تحية لتراث تركيا الطهوي.',
  cuisine: 'Turkish · Ottoman',
  city: 'Muscat, Oman',
  address: 'Al Khuwair, Muscat, Oman',
  phone: '+968 2448 0000',
  whatsapp: '+96824480000',
  rating: 4.6,
  reviews: 842,
  established: 2010,
  hours: {
    weekdays: '12:00 PM – 11:30 PM',
    weekends: '12:00 PM – 1:00 AM',
  },
  highlights: [
    { en: 'Authentic Ottoman Recipes', ar: 'وصفات عثمانية أصيلة' },
    { en: 'Charcoal-Grilled Kebabs', ar: 'كباب مشوي على الفحم' },
    { en: 'Warm Turkish Ambiance', ar: 'أجواء تركية دافئة' },
    { en: 'Homemade Baklava', ar: 'بقلاوة معجونة يدوياً' },
  ],
  marqueeItems: [
    'البيت التركي',
    'AUTHENTIC',
    'OTTOMAN',
    'عدنة كباب',
    'CHARCOAL GRILLED',
    'بقلاوة',
    'HANDCRAFTED',
    'دجاج طاووق',
    'SINCE 2010',
    'لحم عثلي',
    'CRAFTED',
    'MUSCAT',
    'مسقط · عُمان',
  ],
  orbitLabels: [
    { en: 'Adana Kebab', ar: 'عادنة كباب' },
    { en: 'Baklava', ar: 'بقلاوة' },
    { en: 'Tavuk Döner', ar: 'دجاج دونر' },
    { en: 'Pide', ar: 'بيدا' },
    { en: 'Lahmacun', ar: 'لحم عجين' },
    { en: 'Meze', ar: 'مقبلات' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'عادنة كباب',
      nameEn: 'Adana Kebab',
      descAr: 'كباب لحم البقر المفروم بالتوابل التركية مشوي على الفحم مع الأرز والخضروات',
      descEn: 'Spiced ground beef kebab charcoal-grilled on skewers, served with aromatic rice and grilled vegetables',
      price: '4.5 OMR',
      category: 'مشاوي',
      img: `${BASE}/menu-adana.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'دجاج طاووق',
      nameEn: 'Chicken Tawook',
      descAr: 'دجاج متبل بالزبادي والليمون مشوي على الفحم',
      descEn: 'Yoghurt-marinated chicken, charcoal-grilled to perfection',
      price: '3.8 OMR',
      category: 'مشاوي',
      img: `${BASE}/menu-tawook.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'بيتزا البيدا',
      nameEn: 'Turkish Pide',
      descAr: 'خبز تركي مقوّر بالجبن واللحم والأعشاب من الفرن الحجري',
      descEn: 'Boat-shaped flatbread with cheese, lamb and herbs, stone-oven baked',
      price: '3.2 OMR',
      category: 'أفران',
      img: `${BASE}/menu-pide.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'البقلاوة التركية',
      nameEn: 'Turkish Baklava',
      descAr: 'طبقات العجينة الرقيقة مع الفستق الحلبي وشراب العسل محضرة يومياً',
      descEn: 'Phyllo layers filled with pistachios and honey syrup, made fresh daily',
      price: '1.5 OMR',
      category: 'حلويات',
      img: `${BASE}/menu-baklava.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'شوربة العدس',
      nameEn: 'Lentil Soup',
      descAr: 'شوربة عدس تركية كريمية مع النعناع والفلفل الأحمر',
      descEn: 'Creamy Turkish lentil soup finished with dried mint and red pepper',
      price: '1.2 OMR',
      category: 'شوربات',
      img: `${BASE}/menu-soup.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'مقبلات تركية',
      nameEn: 'Turkish Mezze',
      descAr: 'تشكيلة من المقبلات — هومس، مطبل، جبنة بيضاء، وزيتون',
      descEn: 'Selection of spreads — hummus, mutabbal, white cheese and olives',
      price: '2.8 OMR',
      category: 'مقبلات',
      img: `${BASE}/menu-mezze.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠١٠',
      titleEn: 'A Dream Planted',
      titleAr: 'بداية الحلم',
      textEn:
        'Founded in Muscat with a simple mission: to share the authentic flavors of Turkey with the people of Oman.',
      textAr: 'تأسس في مسقط بهدف واحد: مشاركة نكهات تركيا الأصيلة مع أهل عُمان.',
    },
    {
      year: '٢٠١٧',
      titleEn: 'The Grand Hall',
      titleAr: 'القاعة الكبرى',
      textEn:
        'Expanded with a warm Ottoman-inspired dining hall — hand-painted tiles, arched ceilings and the scent of charcoal.',
      textAr: 'توسعنا بقاعة بأجواء عثمانية دافئة — بلاط مرسوم يدوياً وأقواس وعبق الفحم.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Living Table',
      titleAr: 'مائدة حية',
      textEn:
        'Over 14 years of crafting memories in Muscat — every skewer, every pastry, a love letter to Istanbul.',
      textAr: 'أكثر من ١٤ عاماً من صنع الذكريات في مسقط — كل سيخ وكل معجنة رسالة حب إلى إسطنبول.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Ottoman Soul',
      headlineAr: 'روح عثمانية',
      subEn: 'Authentic Turkish cuisine in the heart of Muscat',
      subAr: 'مطبخ تركي أصيل في قلب مسقط',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Fire & Flavor',
      headlineAr: 'نار ونكهة',
      subEn: 'Every kebab charcoal-grilled to perfection',
      subAr: 'كل كباب يُشوى على الفحم بإتقان',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Crafted Daily',
      headlineAr: 'يُصنع يومياً',
      subEn: 'Baklava, pide and mezze made fresh every morning',
      subAr: 'بقلاوة وبيدا ومقبلات طازجة كل صباح',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Dining Hall' },
    { src: `${BASE}/gallery2.jpg`, caption: 'The Grill' },
    { src: `${BASE}/gallery3.jpg`, caption: 'The Pastry Kitchen' },
    { src: `${BASE}/gallery4.jpg`, caption: 'Ottoman Decor' },
    { src: `${BASE}/gallery5.jpg`, caption: 'The Ambiance' },
  ],
  testimonials: [
    {
      nameEn: 'Ahmed Al Balushi',
      nameAr: 'أحمد البلوشي',
      rating: 5,
      textEn: 'The best Adana kebab I\'ve had outside of Turkey. Perfectly spiced, charcoal-grilled — absolutely outstanding.',
      textAr: 'أفضل عادنة كباب تذوقتها خارج تركيا. متبل بإتقان ومشوي على الفحم — رائع جداً.',
      service: 'Adana Kebab',
    },
    {
      nameEn: 'Sara Al Harthy',
      nameAr: 'سارة الحارثي',
      rating: 5,
      textEn: 'The atmosphere is so warm and authentic — the tiled walls and arched ceiling transport you straight to Istanbul.',
      textAr: 'الأجواء دافئة وأصيلة — البلاط والأقواس تنقلك مباشرة إلى إسطنبول.',
      service: 'Dining Experience',
    },
    {
      nameEn: 'Mohammed Al Zadjali',
      nameAr: 'محمد الزدجالي',
      rating: 5,
      textEn: 'Their baklava is extraordinary — crispy, honey-soaked and filled with real pistachios. We order it every visit.',
      textAr: 'البقلاوة استثنائية — مقرمشة ومشبعة بالعسل مع فستق حقيقي. نطلبها في كل زيارة.',
      service: 'Turkish Baklava',
    },
    {
      nameEn: 'Laila Bint Nasser',
      nameAr: 'ليلى بنت ناصر',
      rating: 5,
      textEn: 'Family-friendly, generous portions and genuinely warm service. A gem in Muscat\'s dining scene.',
      textAr: 'مناسب للعائلات، حصص سخية وخدمة دافئة من القلب. جوهرة في مشهد الطعام بمسقط.',
      service: 'Family Dinner',
    },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3651.23!2d58.42762879999999!3d23.5924161!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91ff10136d1e47%3A0xa44b65441e4068ae!2sTurkish%20House%20Restaurant!5e0!3m2!1sen!2som!4v1718000000000!5m2!1sen!2som',
  mapsUrl: 'https://maps.app.goo.gl/m3DuwEwsFyfJ9d7E6',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
export const RED_ACCENT = '#C0392B';
