const BASE = '/tawaheen-alhawa';

export const BUSINESS = {
  nameEn: 'Tawaheen Al Hawa',
  nameAr: 'طواحين الهوا',
  taglineEn: 'Where Tradition Meets the Sky',
  taglineAr: 'حيث يلتقي الأصيل بالسماء',
  descEn:
    'Perched above Amman with panoramic city views, Tawaheen Al Hawa has served authentic Levantine and Jordanian cuisine since 1992. Each dish is a journey through the ancient flavors of the Levant.',
  descAr:
    'تطل طواحين الهوا على عمان من مرتفعات ساحرة، تقدم منذ عام 1992 أصيل المطبخ الأردني والشامي في أجواء لا تُنسى.',
  cuisine: 'Jordanian · Levantine',
  city: 'Amman, Jordan',
  address: 'Rainbow Street, Jabal Al-Weibdeh, Amman',
  phone: '+962 6 000 0000',
  whatsapp: '+96260000000',
  rating: 4.7,
  reviews: 1248,
  established: 1992,
  hours: {
    weekdays: '12:00 PM – 12:00 AM',
    weekends: '12:00 PM – 1:00 AM',
  },
  highlights: [
    { en: 'Panoramic City Views', ar: 'إطلالات بانورامية' },
    { en: 'Authentic Recipes', ar: 'وصفات أصيلة' },
    { en: 'Al Fresco Dining', ar: 'طعام في الهواء الطلق' },
    { en: 'Live Arabic Music', ar: 'موسيقى عربية حية' },
  ],
  marqueeItems: [
    'طواحين الهوا',
    'FRESH',
    'SEASONAL',
    'منسف ملكي',
    'CRAFTED',
    'مزة شامية',
    'LEVANTINE',
    'كباب حلبي',
    'ELEVATED',
    'فتوش طازج',
    'AUTHENTIC',
    'بقلاوة بيتية',
    'SINCE 1992',
  ],
  orbitLabels: [
    { en: 'Mansaf', ar: 'منسف' },
    { en: 'Mezze', ar: 'مزة' },
    { en: 'Kebab', ar: 'كباب' },
    { en: 'Fattoush', ar: 'فتوش' },
    { en: 'Hummus', ar: 'حمص' },
    { en: 'Baklava', ar: 'بقلاوة' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'المنسف الملكي',
      nameEn: 'Royal Mansaf',
      descAr: 'الطبق الوطني الأردني — لحم ضاني مع الجميد والأرز البسمتي',
      descEn: "Jordan's national dish — slow-cooked lamb with jameed sauce over fragrant basmati rice",
      price: '18 JD',
      category: 'مطبق رئيسي',
      img: `${BASE}/menu-mansaf.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'المزة المشكلة',
      nameEn: 'Mixed Mezze',
      descAr: 'حمص، بابا غنوج، تبولة، زيتون ولبنة',
      descEn: 'Hummus, baba ghanoush, tabbouleh, olives & labneh',
      price: '12 JD',
      category: 'مقبلات',
      img: `${BASE}/menu-mezze.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'الكباب الحلبي',
      nameEn: 'Aleppo Kebab',
      descAr: 'كباب مفروم بتوابل حلبية مشوي على الجمر',
      descEn: 'Minced lamb with Aleppo spices, charcoal-grilled',
      price: '15 JD',
      category: 'مشاوي',
      img: `${BASE}/menu-kebab.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'الفتوش الشامي',
      nameEn: 'Levantine Fattoush',
      descAr: 'سلطة أعشاب طازجة مع خبز محمص وصلصة الرمان',
      descEn: 'Fresh herb salad with crispy bread and pomegranate dressing',
      price: '8 JD',
      category: 'سلطات',
      img: `${BASE}/menu-fattoush.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'حمص بالطحينة',
      nameEn: 'Hummus Tahini',
      descAr: 'حمص كريمي محضر يومياً بطحينة مميزة وزيت زيتون',
      descEn: 'Freshly prepared creamy hummus with premium tahini and olive oil',
      price: '6 JD',
      category: 'مقبلات',
      img: `${BASE}/menu-hummus.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'البقلاوة البيتية',
      nameEn: 'Homemade Baklava',
      descAr: 'بقلاوة بالفستق والعسل محضرة يومياً في مطبخنا',
      descEn: 'Pistachio and honey baklava made fresh daily',
      price: '7 JD',
      category: 'حلويات',
      img: `${BASE}/menu-baklava.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '١٩٩٢',
      titleEn: 'The Beginning',
      titleAr: 'البداية',
      textEn:
        'Founded on a hilltop in Amman with a vision to preserve authentic Jordanian flavors for generations.',
      textAr: 'تأسست على تلة في عمان برؤية للحفاظ على النكهات الأردنية الأصيلة للأجيال القادمة.',
    },
    {
      year: '٢٠٠٥',
      titleEn: 'The Terrace',
      titleAr: 'الشرفة',
      textEn:
        "Expanded to an iconic open-air terrace — 270° views of Amman's glittering skyline at dusk.",
      textAr: 'توسعنا إلى الشرفة الشهيرة في الهواء الطلق مع إطلالات 270° على أفق عمان المضيء.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Living Legacy',
      titleAr: 'الإرث الحي',
      textEn:
        'Over 30 years of crafting memories above the city — every dish a love letter to the Levant.',
      textAr: 'أكثر من 30 عاماً من صنع الذكريات فوق المدينة — كل طبق رسالة حب إلى الشام.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Above The City',
      headlineAr: 'فوق المدينة',
      subEn: 'Levantine cuisine with panoramic Amman views',
      subAr: 'مطبخ شامي أصيل مع إطلالات بانورامية على عمان',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Timeless Flavors',
      headlineAr: 'نكهات خالدة',
      subEn: 'Recipes passed down through generations',
      subAr: 'وصفات متوارثة عبر الأجيال',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Crafted With Soul',
      headlineAr: 'بُني بالروح',
      subEn: 'Where every meal becomes a memory',
      subAr: 'حيث تتحول كل وجبة إلى ذكرى',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Terrace' },
    { src: `${BASE}/gallery2.jpg`, caption: 'The Ambiance' },
    { src: `${BASE}/gallery3.jpg`, caption: 'From The Kitchen' },
    { src: `${BASE}/gallery4.jpg`, caption: 'The Mezze' },
    { src: `${BASE}/gallery5.jpg`, caption: 'The Evenings' },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3383.532!2d35.8641!3d31.9920881!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x151ca1cddd409dd5%3A0x6e6337f7366264fd!2sTawaheen%20Al%20Hawa!5e0!3m2!1sen!2sjo!4v1718000000000!5m2!1sen!2sjo',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
