const BASE = '/aroos-al-bahar';

export const BUSINESS = {
  nameEn: 'Aroos Al Bahar',
  nameAr: 'عروس البحر',
  taglineEn: 'Bride of the Sea, Soulful Omani Flavours',
  taglineAr: 'نكهات عُمانية أصيلة من قلب البحر',
  descEn:
    'Nestled in the heart of Muscat, Aroos Al Bahar brings the ocean to your table — premium grilled fish, Omani seafood traditions, and fresh-caught specialties in a warm sea-breeze ambiance.',
  descAr:
    'في قلب مسقط، يُقدّم مطعم عروس البحر أفضل المأكولات البحرية المشوية وأعرق الوصفات العُمانية الأصيلة في أجواء تعبق برائحة البحر.',
  cuisine: 'Omani Seafood · Grills',
  city: 'Muscat, Oman',
  address: 'Muscat, Sultanate of Oman',
  phone: '+968 00 000 000',
  whatsapp: '96800000000',
  rating: 4.6,
  reviews: 850,
  established: 2010,
  hours: {
    weekdays: '12:00 PM – 12:00 AM',
    weekends: '12:00 PM – 1:00 AM',
  },
  highlights: [
    { en: 'Fresh-Caught Daily', ar: 'صيد يومي طازج' },
    { en: 'Authentic Omani Grills', ar: 'مشاوي عُمانية أصيلة' },
    { en: 'Seaside Ambiance', ar: 'أجواء بحرية فريدة' },
    { en: 'Family Gatherings', ar: 'مجالس عائلية دافئة' },
  ],
  marqueeItems: [
    'عروس البحر',
    'FRESH CATCH',
    'OMANI GRILLS',
    'سمك مشوي',
    'SEASIDE',
    'هريس بحري',
    'CRAFTED',
    'صيد اليوم',
    'AUTHENTIC',
    'سالونة سمك',
    'SINCE 2010',
    'لقيمات',
    'OCEAN TO TABLE',
    'مسقط',
  ],
  orbitLabels: [
    { en: 'Grilled Fish', ar: 'سمك مشوي' },
    { en: 'Harees', ar: 'هريس' },
    { en: 'Saloona', ar: 'سالونة' },
    { en: 'Prawns', ar: 'روبيان' },
    { en: 'Luqaimat', ar: 'لقيمات' },
    { en: 'Mixed Grill', ar: 'مشاوي مشكلة' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'سمك مشوي على الفحم',
      nameEn: 'Charcoal Grilled Fish',
      descAr: 'صيد اليوم الطازج متبل بالتوابل العُمانية ومشوي على الفحم الطبيعي',
      descEn: "Today's fresh catch marinated in Omani spices and charcoal-grilled to perfection",
      price: '8 OMR',
      category: 'مشاوي رئيسية',
      img: `${BASE}/menu-samak.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'مشاوي مشكلة',
      nameEn: 'Mixed Seafood Grill',
      descAr: 'تشكيلة من الروبيان والسمك والحبار مشوية على الفحم بتوابل خاصة',
      descEn: 'Assorted prawns, fish & calamari grilled with our signature spice blend',
      price: '12 OMR',
      category: 'مشاوي',
      img: `${BASE}/menu-mashawi.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'هريس بحري',
      nameEn: 'Seafood Harees',
      descAr: 'هريس تقليدي عُماني بالأسماك الطازجة وزيت الليمون والكزبرة',
      descEn: 'Traditional Omani harees enriched with fresh fish, lime oil and coriander',
      price: '5 OMR',
      category: 'أطباق تقليدية',
      img: `${BASE}/menu-harees.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'سالونة سمك عُمانية',
      nameEn: 'Omani Fish Saloona',
      descAr: 'مرق سمك عطري بالخضروات والتوابل العُمانية الأصيلة يُقدّم مع الأرز',
      descEn: 'Aromatic fish stew with vegetables and authentic Omani spices served with rice',
      price: '6 OMR',
      category: 'مرق وشوربة',
      img: `${BASE}/menu-saloona.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'روبيان مشوي بالثوم',
      nameEn: 'Garlic Butter Prawns',
      descAr: 'روبيان طازج كبير الحجم مشوي بزبدة الثوم وعصير الليمون',
      descEn: 'Jumbo fresh prawns grilled with garlic butter and fresh lemon juice',
      price: '10 OMR',
      category: 'مشاوي',
      img: `${BASE}/menu-rokhal.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'لقيمات بالعسل',
      nameEn: 'Honey Luqaimat',
      descAr: 'كرات العجين الذهبية المقرمشة مع عسل الدبس والسمسم — حلوى عُمانية أصيلة',
      descEn: 'Crispy golden dough balls drizzled with date molasses and sesame',
      price: '3 OMR',
      category: 'حلويات',
      img: `${BASE}/menu-luqaimat.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠١٠',
      titleEn: 'Born by the Sea',
      titleAr: 'وُلدنا من البحر',
      textEn:
        'Founded in Muscat with one vision: honour the Omani tradition of fresh-caught seafood, cooked with the spices passed down through fishing families for generations.',
      textAr:
        'تأسسنا في مسقط برؤية واحدة: تكريم تقاليد الصيد العُمانية الأصيلة، وإعداد الطعام بتوابل توارثتها عائلات الصيادين جيلاً بعد جيل.',
    },
    {
      year: '٢٠١٦',
      titleEn: 'The Ocean Kitchen',
      titleAr: 'مطبخ المحيط',
      textEn:
        'We expanded to welcome whole families — wide communal tables, open charcoal grills, and the aroma of the sea filling every corner.',
      textAr:
        'وسّعنا مطبخنا لاستقبال العائلات — طاولات مشتركة فسيحة، مشاوي فحم مفتوحة، وعبق البحر يملأ كل ركن.',
    },
    {
      year: 'اليوم',
      titleEn: "Muscat's Sea Table",
      titleAr: 'مائدة مسقط البحرية',
      textEn:
        "Over a decade of serving Muscat's finest seafood — every plate a celebration of Oman's rich coastal heritage.",
      textAr:
        'أكثر من عقد من تقديم أفضل المأكولات البحرية في مسقط — كل طبق احتفاء بتراث عُمان الساحلي العريق.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Bride of The Sea',
      headlineAr: 'عروس البحر',
      subEn: 'Premium Omani seafood grilled over charcoal in Muscat',
      subAr: 'أفضل المأكولات البحرية العُمانية مشوية على الفحم في مسقط',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Ocean Fresh',
      headlineAr: 'طازج من البحر',
      subEn: 'Daily catch · Omani spices · Charcoal fire',
      subAr: 'صيد اليوم · توابل عُمانية · فحم طبيعي',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Crafted With Fire',
      headlineAr: 'صُنع بالنار',
      subEn: 'Where every meal becomes a coastal memory',
      subAr: 'حيث تتحول كل وجبة إلى ذكرى ساحلية',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Ocean Grill' },
    { src: `${BASE}/gallery2.jpg`, caption: 'Family Ambiance' },
    { src: `${BASE}/gallery3.jpg`, caption: 'From the Kitchen' },
    { src: `${BASE}/gallery4.jpg`, caption: 'Fresh Catch' },
    { src: `${BASE}/gallery5.jpg`, caption: 'Coastal Evenings' },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3656.2!2d58.5613007!3d23.6247647!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91f78ebad805e1%3A0x96ee5e0859bdd2d4!2sAroos%20Al%20Bahar%20Fish%20Restaurant!5e0!3m2!1sen!2som!4v1718000000000!5m2!1sen!2som',
  testimonials: [
    {
      nameEn: 'Ahmad Al Balushi',
      textEn: 'The best grilled fish I have had in Muscat. The charcoal flavour is incredible and the Omani spices are exactly like home cooking.',
      textAr: 'أفضل سمك مشوي تذوقته في مسقط. نكهة الفحم رائعة والتوابل العُمانية تماماً كالطبخ المنزلي.',
      rating: 5,
      service: 'Grilled Fish',
    },
    {
      nameEn: 'Fatima Al Rashdi',
      textEn: 'Aroos Al Bahar never disappoints. We come every Friday as a family — the saloona and luqaimat are a must!',
      textAr: 'عروس البحر لا تخيب أبدًا. نأتي كل جمعة كعائلة — السالونة واللقيمات لا غنى عنهما!',
      rating: 5,
      service: 'Family Dining',
    },
    {
      nameEn: 'Mohammed Al Hinai',
      textEn: 'Authentic Omani taste at its finest. The mixed seafood grill is worth every riyal. Highly recommended for visitors to Muscat.',
      textAr: 'طعم عُماني أصيل بامتياز. المشاوي المشكلة تستحق كل ريال. أنصح بها بشدة لزوار مسقط.',
      rating: 5,
      service: 'Mixed Grill',
    },
    {
      nameEn: 'Sara Al Maawali',
      textEn: 'The atmosphere is wonderful and the seafood is super fresh. You can tell everything is prepared the same day.',
      textAr: 'الأجواء رائعة والمأكولات البحرية طازجة للغاية. يُلاحَظ أن كل شيء يُحضَّر في نفس اليوم.',
      rating: 4,
      service: 'Fresh Seafood',
    },
  ],
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
