const BASE = '/sukoon-muscat';

export const BUSINESS = {
  nameEn: 'Sukoon Restaurant',
  nameAr: 'مطعم سكون',
  taglineEn: 'Serenity on the Marina',
  taglineAr: 'سكون على المارينا',
  descEn:
    'Perched on the Al Mouj Marina in Muscat, Sukoon blends Omani tradition with Mediterranean craft — where the salt breeze meets slow-cooked flavors and every meal becomes a memory.',
  descAr:
    'على أرصفة مرسى الموج في مسقط، يمزج سكون بين الأصيل العُماني والمتوسطي الرفيع — حيث يلتقي نسيم البحر بالنكهات المطبوخة بحب.',
  cuisine: 'Omani · Mediterranean',
  city: 'Muscat, Oman',
  address: 'Al Mouj Marina, Marsa 1, 18th November Street, Muscat 113, Oman',
  phone: '+968 9939 3359',
  whatsapp: '96899393359',
  rating: 4.8,
  reviews: 380,
  established: 2021,
  hours: {
    weekdays: '12:00 PM – 11:00 PM',
    weekends: '12:00 PM – 11:30 PM',
  },
  highlights: [
    { en: 'Al Mouj Marina Views', ar: 'إطلالات على مرسى الموج' },
    { en: 'Omani Fusion Cuisine', ar: 'مطبخ عُماني متميز' },
    { en: 'Waterfront Terrace', ar: 'تراس على الواجهة البحرية' },
    { en: 'Family & Fine Dining', ar: 'عائلي وراقي' },
  ],
  marqueeItems: [
    'مطعم سكون',
    'FRESH',
    'CRAFTED',
    'شيوه ريزوتو',
    'SEASONAL',
    'سلمون فلورنتين',
    'MARINA VIEWS',
    'روبيان باربيكيو',
    'OMANI FUSION',
    'باستا وردية',
    'ELEVATED',
    'AL MOUJ',
    'سكون',
    'MUSCAT',
  ],
  orbitLabels: [
    { en: 'Shiwa Risotto', ar: 'شيوه ريزوتو' },
    { en: 'Salmon', ar: 'سلمون' },
    { en: 'BBQ Shrimp', ar: 'روبيان' },
    { en: 'Calamari', ar: 'كاليماري' },
    { en: 'Pink Pasta', ar: 'باستا وردية' },
    { en: 'Om Ali', ar: 'أم علي' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'شيوه ريزوتو',
      nameEn: 'Shiwa Risotto',
      descAr: 'ريزوتو كريمي ملهم بالشيوه العُماني — لحم ضاني مطهو ببطء مع توابل البهارات العربية',
      descEn: 'Creamy risotto inspired by Omani Shuwa — slow-braised lamb with warming Arabian spices',
      price: '12 OMR',
      category: 'مطبق رئيسي',
      img: `${BASE}/menu-shiwa.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'سلمون فلورنتين',
      nameEn: 'Salmon Florentine',
      descAr: 'سلمون طازج مشوي بصلصة الإسبانخ الكريمية وليمون الحمضيات',
      descEn: 'Fresh grilled salmon fillet over creamy florentine spinach sauce with citrus',
      price: '10 OMR',
      category: 'أطباق بحرية',
      img: `${BASE}/menu-salmon.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'روبيان باربيكيو',
      nameEn: 'BBQ Shrimp',
      descAr: 'روبيان ملكي مشوي على الجمر بتتبيلة الثوم والليمون والأعشاب',
      descEn: 'Royal shrimp charcoal-grilled with garlic, lemon, and fresh herb marinade',
      price: '9 OMR',
      category: 'أطباق بحرية',
      img: `${BASE}/menu-shrimp.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'باستا وردية',
      nameEn: 'Pink Pasta',
      descAr: 'باستا فريش بصلصة الطماطم الكريمية مع جبنة البارميزان المحروقة',
      descEn: 'Fresh pasta in a velvety tomato cream sauce, finished with torched parmesan',
      price: '7 OMR',
      category: 'باستا',
      img: `${BASE}/menu-pasta.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'كاليماري',
      nameEn: 'Crispy Calamari',
      descAr: 'حلقات كاليماري مقرمشة بتتبيلة التوابل مع صلصة الأيولي المليمون',
      descEn: 'Golden fried calamari rings with spiced coating and lemon aioli',
      price: '5.5 OMR',
      category: 'مقبلات',
      img: `${BASE}/menu-calamari.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'أم علي',
      nameEn: 'Om Ali',
      descAr: 'حلوى أم علي الكلاسيكية بالمكسرات والزبيب والكريمة المحمرة',
      descEn: 'Classic bread pudding with nuts, raisins and golden baked cream',
      price: '3.5 OMR',
      category: 'حلويات',
      img: `${BASE}/menu-omali.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠٢١',
      titleEn: 'Born on the Water',
      titleAr: 'وُلد على الماء',
      textEn:
        'Sukoon opened its doors on the Al Mouj Marina — a vision of stillness and flavor where the Omani sea breeze sets the pace.',
      textAr:
        'فتح سكون أبوابه على مرسى الموج — رؤية من السكينة والنكهة حيث ينسّق نسيم البحر العُماني الإيقاع.',
    },
    {
      year: '٢٠٢٣',
      titleEn: 'The Fusion Chapter',
      titleAr: 'فصل الدمج',
      textEn:
        'Our chefs wove Omani heritage into Mediterranean technique — Shuwa risotto, saffron sea bass, and the legendary Om Ali.',
      textAr:
        'نسج طهاتنا الموروث العُماني في تقنية متوسطية — ريزوتو الشيوه، قاروص الزعفران، وأم علي الأسطوري.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Place to Return',
      titleAr: 'مكان للعودة',
      textEn:
        'Sukoon is not just a restaurant — it is a ritual. The marina at sunset, the first bite, the last sip of Arabic coffee.',
      textAr:
        'سكون ليس مجرد مطعم — بل طقس. المرسى عند الغروب، أول لقمة، آخر فنجان قهوة عربية.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Serenity',
      headlineAr: 'سكون',
      subEn: 'Omani fusion on the Al Mouj Marina, Muscat',
      subAr: 'مطبخ عُماني متوسطي على مرسى الموج',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Marina Soul',
      headlineAr: 'روح المرسى',
      subEn: 'Where the sea breeze meets every flavor',
      subAr: 'حيث يلتقي نسيم البحر بكل نكهة',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Crafted Calm',
      headlineAr: 'هدوء المُصنوع',
      subEn: 'Every dish a moment worth pausing for',
      subAr: 'كل طبق لحظة تستحق التوقف',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Marina' },
    { src: `${BASE}/gallery2.jpg`, caption: 'The Ambiance' },
    { src: `${BASE}/gallery3.jpg`, caption: 'From the Kitchen' },
    { src: `${BASE}/gallery4.jpg`, caption: 'The Terrace' },
    { src: `${BASE}/gallery5.jpg`, caption: 'Evening Light' },
  ],
  testimonials: [
    {
      nameEn: 'Tess Pollard',
      rating: 5,
      textEn: 'The Omani food was some of the best we had all trip. Beautiful presentation and absolutely delicious.',
      textAr: 'الطعام العُماني كان من أفضل ما تذوقناه في رحلتنا. تقديم رائع ومذاق لا يُنسى.',
      tag: 'Marina Dinner',
    },
    {
      nameEn: 'Vladimir D.',
      rating: 5,
      textEn: 'The service is unbeatable — every time I feel like they are just waiting for me.',
      textAr: 'الخدمة لا مثيل لها — في كل مرة أشعر أنهم ينتظرونني تحديداً.',
      tag: 'Regular Guest',
    },
    {
      nameEn: 'Asitha S.',
      rating: 5,
      textEn: 'Very peaceful ambience to relax with a great marina view to enjoy your coffee.',
      textAr: 'أجواء هادئة جداً للاسترخاء مع إطلالة رائعة على المرسى وقهوة لا تُنسى.',
      tag: 'Afternoon Visit',
    },
    {
      nameEn: 'Ulrike K.',
      rating: 5,
      textEn: 'Excellent service, amazing food, super friendly staff and fast service. Highly recommend!',
      textAr: 'خدمة ممتازة، طعام رائع، طاقم عمل ودود للغاية. أنصح به بشدة!',
      tag: 'Family Dinner',
    },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.5!2d58.2657432!3d23.6302939!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e8dfd5f42a97f7d%3A0xfc571b19a4df4e28!2sSukoon%20Restaurant!5e0!3m2!1sen!2som!4v1718900000000!5m2!1sen!2som',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
