const BASE = '/foodpark-asian';

export const BUSINESS = {
  nameEn: 'Foodpark Asian Restaurant',
  nameAr: 'فودبارك مطعم آسيوي',
  taglineEn: 'Flavors of Asia, Heart of Muscat',
  taglineAr: 'نكهات آسيا في قلب مسقط',
  descEn:
    'Nestled in Ghubra, Muscat, Foodpark brings together the finest flavors of China, Thailand, India and the Grill — a culinary journey across Asia served with warm Omani hospitality.',
  descAr:
    'في قلب الغبرة بمسقط، يجمع فودبارك أرقى نكهات الصين وتايلاند والهند في تجربة آسيوية لا تُنسى، مقدَّمة بدفء الضيافة العُمانية.',
  cuisine: 'Asian Fusion · Chinese · Thai · Indian · Grill',
  city: 'Muscat, Oman',
  address: 'Al Dheyafah Street, Ghubra North, Near Indian School Ghubrah, Muscat, Oman',
  phone: '+968 9139 1326',
  whatsapp: '+96891391326',
  rating: 4.5,
  reviews: 18,
  established: 2017,
  hours: {
    weekdays: '11:00 AM – 3:30 PM · 6:30 PM – 11:00 PM',
    weekends: '11:00 AM – 3:30 PM · 6:30 PM – 11:30 PM',
  },
  highlights: [
    { en: 'Butter Chicken', ar: 'بتر تشيكن' },
    { en: 'Tandoori Grill', ar: 'تنور مشوي' },
    { en: 'Thai Soups', ar: 'حساء تايلاندي' },
    { en: 'Bamboo Biryani', ar: 'برياني البامبو' },
  ],
  marqueeItems: [
    'فودبارك',
    'FRESH',
    'CRAFTED',
    'برياني البامبو',
    'ASIAN FUSION',
    'تنوري تيكا',
    'SEASONAL',
    'Butter Chicken',
    'AUTHENTIC',
    'حساء تايلاندي',
    'MUSCAT',
    'كباب أصيل',
    'SINCE 2017',
    'Noodles',
  ],
  orbitLabels: [
    { en: 'Biryani', ar: 'برياني' },
    { en: 'Butter Chicken', ar: 'بتر تشيكن' },
    { en: 'Tandoori', ar: 'تنوري' },
    { en: 'Thai Soup', ar: 'حساء تاي' },
    { en: 'Noodles', ar: 'نودلز' },
    { en: 'Kabab', ar: 'كباب' },
  ],
  menu: [
    {
      id: 1,
      nameAr: 'برياني البامبو',
      nameEn: 'Bamboo Biryani',
      descAr: 'برياني الخروف الأسطوري مطبوخ داخل أنبوب البامبو — طبق لا يُنسى',
      descEn: 'Legendary mutton biryani slow-cooked inside a bamboo tube — a must-try signature',
      price: '3.5 OMR',
      category: 'Main Course',
      img: `${BASE}/menu-biryani.jpg`,
      featured: true,
      size: 'large',
    },
    {
      id: 2,
      nameAr: 'بتر تشيكن',
      nameEn: 'Butter Chicken',
      descAr: 'دجاج طري في صلصة الزبدة الكريمية — الفائز الواضح',
      descEn: 'Tender chicken in velvety butter sauce — a clear crowd winner',
      price: '2.8 OMR',
      category: 'Indian',
      img: `${BASE}/menu-butter-chicken.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 3,
      nameAr: 'تنوري تيكا',
      nameEn: 'Tandoori Tikka',
      descAr: 'قطع الدجاج المتبلة مشوية على حرارة التنور الأصيلة',
      descEn: 'Marinated chicken grilled in a traditional tandoor oven — smoky perfection',
      price: '2.5 OMR',
      category: 'Tandoor',
      img: `${BASE}/menu-tikka.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 4,
      nameAr: 'حساء تايلاندي',
      nameEn: 'Thai Soup',
      descAr: 'حساء تايلاندي فاخر بنكهات جوز الهند والليمون والتوابل الآسيوية',
      descEn: 'Aromatic Thai broth with coconut, lemongrass & Asian spices',
      price: '1.8 OMR',
      category: 'Thai',
      img: `${BASE}/menu-thai-soup.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 5,
      nameAr: 'كباب أصيل',
      nameEn: 'Authentic Kababs',
      descAr: 'كباب مفروم بتوابل خاصة مشوي على الجمر — أصيل وشهي',
      descEn: 'Hand-spiced minced kababs charcoal-grilled to smoky perfection',
      price: '2.2 OMR',
      category: 'Grill',
      img: `${BASE}/menu-kebab.jpg`,
      featured: false,
      size: 'small',
    },
    {
      id: 6,
      nameAr: 'نودلز آسيوية',
      nameEn: 'Asian Noodles',
      descAr: 'نودلز آسيوية طازجة بالخضار والصلصة السرية',
      descEn: 'Fresh tossed noodles with crisp vegetables in our secret sauce',
      price: '1.9 OMR',
      category: 'Chinese',
      img: `${BASE}/menu-noodles.jpg`,
      featured: false,
      size: 'small',
    },
  ],
  story: [
    {
      year: '٢٠١٧',
      titleEn: 'The First Plate',
      titleAr: 'أول طبق',
      textEn:
        'Born in Ghubra with a bold mission — to bring the authentic soul of Asian cuisine to Muscat\'s dining scene.',
      textAr: 'وُلد في الغبرة بمهمة جريئة — إحضار الروح الأصيلة للمطبخ الآسيوي إلى مسقط.',
    },
    {
      year: '٢٠٢٠',
      titleEn: 'Fusion Mastered',
      titleAr: 'إتقان الفيوجن',
      textEn:
        'Blending Chinese, Thai, Indian & Grill into one seamless menu beloved by Muscat\'s diverse community.',
      textAr: 'دمج الصيني والتايلاندي والهندي والمشاوي في قائمة واحدة يحبها متنوعو مسقط.',
    },
    {
      year: 'اليوم',
      titleEn: 'A Muscat Favourite',
      titleAr: 'المفضل في مسقط',
      textEn:
        'From bamboo biryani to butter chicken — every dish is a love letter to the richness of Asia.',
      textAr: 'من برياني البامبو إلى البتر تشيكن — كل طبق رسالة حب لثراء آسيا.',
    },
  ],
  heroSlides: [
    {
      img: `${BASE}/hero1.jpg`,
      headlineEn: 'Taste Asia',
      headlineAr: 'تذوق آسيا',
      subEn: 'Chinese · Thai · Indian · Grill — all under one roof in Muscat',
      subAr: 'صيني · تايلاندي · هندي · مشاوي — كلها تحت سقف واحد في مسقط',
    },
    {
      img: `${BASE}/hero2.jpg`,
      headlineEn: 'Crafted With Fire',
      headlineAr: 'مصنوع بالنار',
      subEn: 'Tandoor, wok & grill — the ancient techniques, perfected',
      subAr: 'التنور والوك والمشوي — التقنيات القديمة في أبهى صورها',
    },
    {
      img: `${BASE}/hero3.jpg`,
      headlineEn: 'Soul Of Asia',
      headlineAr: 'روح آسيا',
      subEn: 'Where every meal becomes an unforgettable journey',
      subAr: 'حيث تتحول كل وجبة إلى رحلة لا تُنسى',
    },
  ],
  galleryImages: [
    { src: `${BASE}/gallery1.jpg`, caption: 'The Kitchen' },
    { src: `${BASE}/gallery2.jpg`, caption: 'The Ambiance' },
    { src: `${BASE}/gallery3.jpg`, caption: 'Signature Dishes' },
    { src: `${BASE}/gallery4.jpg`, caption: 'The Experience' },
    { src: `${BASE}/gallery5.jpg`, caption: 'The Flavors' },
  ],
  testimonials: [
    {
      name: 'Ali A.',
      stars: 5,
      text: 'Amazing food and service — the staff are so welcoming. The noodles are especially incredible.',
    },
    {
      name: 'Md Kamal M.',
      stars: 5,
      text: 'Best butter chicken and Tandoori Tikka I\'ve ever tried. A clear winner for me.',
    },
    {
      name: 'Mohamed R.',
      stars: 5,
      text: 'Authentic kababs are awesome. Thai soup is extremely good — highly recommend both.',
    },
    {
      name: 'Jofeena J.',
      stars: 5,
      text: 'Must-try Asian resto with very reasonable pricing. Thai, Indian, Chinese — all top quality.',
    },
    {
      name: 'Vinu C.',
      stars: 5,
      text: 'Mutton Bamboo Biryani is really awesome and a must try. Highly recommended!',
    },
  ],
  dishOrbitImg: `${BASE}/dish-orbit.jpg`,
  storyBg: `${BASE}/hero2.jpg`,
  reservationBg: `${BASE}/gallery1.jpg`,
  mapsEmbedSrc:
    'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.8!2d58.3937365!3d23.589799!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e91ffcaf64ea5ef%3A0x171d0dcade617211!2sFoodpark%20Asian%20Restaurant!5e0!3m2!1sen!2som!4v1718000000000!5m2!1sen!2som',
};

export const GOLD = '#C9A96E';
export const GOLD_LIGHT = '#E8C87A';
export const DARK_BG = '#0A0908';
export const CREAM = '#FAF7F2';
